"""Best-effort Sigma YAML export for simple DSL rules (A3). Clearly marked; thresholds and sequences are not mapped."""

from __future__ import annotations

from typing import Any

from app.prediction.signals import Condition
from app.rules.dsl import RuleDefinition

HEADER = "# Best-effort Sigma export generated by AEGIS SOC. Field names are AEGIS fields; verify before use."
_MODIFIERS = {
    "equals": "",
    "in": "",
    "contains": "|contains",
    "startswith": "|startswith",
    "endswith": "|endswith",
    "cidr": "|cidr",
    "regex": "|re",
    "gt": "|gt",
    "gte": "|gte",
    "lt": "|lt",
    "lte": "|lte",
}
_LEVELS = {"LOW": "low", "MEDIUM": "medium", "HIGH": "high", "CRITICAL": "critical"}


def _quote(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{text}"'


def _selection(name: str, kinds: tuple[str, ...] | None, conditions: tuple[Condition, ...]) -> list[str]:
    lines = [f"  {name}:"]
    if kinds:
        lines.append("    kind:")
        lines.extend(f"      - {_quote(kind)}" for kind in kinds)
    for condition in conditions:
        values = condition.value if isinstance(condition.value, list) else [condition.value]
        lines.append(f"    {condition.field}{_MODIFIERS[condition.op]}:")
        lines.extend(f"      - {_quote(value)}" for value in values)
    return lines


def to_sigma(rule_id: str, version: int, definition: RuleDefinition) -> tuple[str, list[str]]:
    logic = definition.logic
    warnings: list[str] = []
    if logic.sequence:
        warnings.append("The ordered sequence cannot be expressed in basic Sigma; only the first step is exported")
    if logic.threshold.type != "count" or logic.threshold.value > 1:
        warnings.append(
            f"The threshold ({logic.threshold.type} >= {logic.threshold.value} within {logic.window_seconds}s, "
            f"grouped by {', '.join(logic.group_by)}) is not mapped; use a Sigma correlation rule or the AEGIS JSON"
        )
    lines = [HEADER]
    lines.extend(f"# WARNING: {warning}" for warning in warnings)
    lines += [
        f"title: {_quote(definition.name)}",
        f"id: {_quote(f'aegis-{rule_id.lower()}-v{version}')}",
        "status: experimental",
        f"description: {_quote(definition.description)}",
        "author: AEGIS SOC export",
        "logsource:",
        "  product: aegis",
        "  service: normalized-events",
        "detection:",
    ]
    if logic.sequence:
        first = logic.sequence[0]
        lines += _selection("selection", first.kinds, (*logic.conditions, *first.conditions))
    else:
        lines += _selection("selection", logic.kinds, logic.conditions)
    if logic.exclusions:
        lines += _selection("filter", None, logic.exclusions)
        lines.append("  condition: selection and not filter")
    else:
        lines.append("  condition: selection")
    if definition.known_false_positives:
        lines.append("falsepositives:")
        lines.extend(f"  - {_quote(item)}" for item in definition.known_false_positives)
    lines.append(f"level: {_LEVELS[definition.severity]}")
    if definition.techniques:
        lines.append("tags:")
        lines.extend(f"  - attack.{technique.lower()}" for technique in definition.techniques)
    return "\n".join(lines) + "\n", warnings
